name: Design Tokens CI

on:
  push:
    paths:
      - 'design-tokens/figma-tokens.json'
      - 'design-tokens/build-tokens.cjs'
  pull_request:
    paths:
      - 'design-tokens/figma-tokens.json'
      - 'design-tokens/build-tokens.cjs'

jobs:
  validate-tokens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build tokens
        run: npm run build:tokens

      - name: Check for changes
        run: |
          git diff --exit-code design-tokens/build/ || (echo "Token build files are out of date. Please run 'npm run build:tokens' locally and commit the changes." && exit 1)

      - name: Validate SCSS
        run: |
          npx sass design-tokens/build/variables.scss temp.css
          rm temp.css

      - name: Validate JavaScript
        run: |
          node -c design-tokens/build/tokens.js

      - name: Validate TypeScript
        run: |
          ./node_modules/.bin/tsc --noEmit design-tokens/build/tokens.d.ts 